### ISSUE TITLE
Docker DNS resolution not working

### ISSUE THREAD

**Issue by fran-olivares** [fr4nsys/umbrel-arch#1]
docker logs nextcloud-app_proxy-1
yarn run v1.22.19
$ node ./bin/www
[HPM] Proxy created: /  -> http://nextcloud_web_1:80
Waiting for nextcloud_web_1:80 to open...
Error wating for port: "The address 'nextcloud_web_1' cannot be found"
Retrying...
Error wating for port: "The address 'nextcloud_web_1' cannot be found"
Retrying...
[arch@manjaroumbrelvm ~]$ sudo docker network inspect umbrel_main_networksudo docker logs nextcloud-web-1
[]
Error response from daemon: network umbrel_main_networksudo not found
Error response from daemon: network docker not found
Error response from daemon: network logs not found
Error response from daemon: network nextcloud-web-1 not found 

<details>
<summary>debug</summary>
./debug 
=====================
= Umbrel debug info =
=====================

Umbrel version
--------------
0.5.4

Memory usage
------------
               total        used        free      shared  buff/cache   available
Mem:            4,1G        1,9G        125M         13M        2,4G        2,2G
Swap:           5,4G         12K        5,4G

total: 46.1%
system: 37.8%
nextcloud: 8.3%

Memory monitor logs
-------------------
2024-02-11 02:06:23 Memory monitor running!

Filesystem information
----------------------
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        44G   11G   32G  26% /
/dev/sda1        44G   11G   32G  26% /

Karen logs
----------

 f72956aacb79 Extracting [=============================================>     ]  182.2MB/202.3MB
 f72956aacb79 Extracting [==============================================>    ]  188.8MB/202.3MB
 f72956aacb79 Extracting [===============================================>   ]  191.6MB/202.3MB
 f72956aacb79 Extracting [================================================>  ]    195MB/202.3MB
 f72956aacb79 Extracting [================================================>  ]  197.8MB/202.3MB
 f72956aacb79 Extracting [=================================================> ]  200.5MB/202.3MB
 f72956aacb79 Extracting [=================================================> ]  201.1MB/202.3MB
 f72956aacb79 Extracting [=================================================> ]  201.7MB/202.3MB
 f72956aacb79 Extracting [==================================================>]  202.3MB/202.3MB
 f72956aacb79 Pull complete 
 be0d62eabf39 Extracting [==================================================>]  3.613kB/3.613kB
 be0d62eabf39 Extracting [==================================================>]  3.613kB/3.613kB
 be0d62eabf39 Pull complete 
 1f67c712d445 Extracting [==================================================>]  2.392kB/2.392kB
 1f67c712d445 Extracting [==================================================>]  2.392kB/2.392kB
 1f67c712d445 Pull complete 
 cron Pulled 
Starting app nextcloud...
Executing hook: /home/arch/umbrel/app-data/nextcloud/hooks/pre-start
time="2024-02-11T02:10:00+01:00" level=warning msg="network default: network.external.name is deprecated. Please set network.name with external: true"
 Container nextcloud-redis-1  Creating
 Container nextcloud-db-1  Creating
 Container nextcloud-app_proxy-1  Creating
 Container nextcloud-db-1  Created
 Container nextcloud-app_proxy-1  Created
 Container nextcloud-redis-1  Created
 Container nextcloud-web-1  Creating
 Container nextcloud-cron-1  Creating
 Container nextcloud-web-1  Created
 Container nextcloud-cron-1  Created
 Container nextcloud-redis-1  Starting
 Container nextcloud-db-1  Starting
 Container nextcloud-app_proxy-1  Starting
 Container nextcloud-db-1  Started
 Container nextcloud-redis-1  Started
 Container nextcloud-web-1  Starting
 Container nextcloud-cron-1  Starting
 Container nextcloud-app_proxy-1  Started
 Container nextcloud-web-1  Started
 Container nextcloud-cron-1  Started
Executing hook: /home/arch/umbrel/app-data/nextcloud/hooks/post-start
Waiting for file (/home/arch/umbrel/app-data/nextcloud/data/nextcloud/.htaccess) to exist...
.htaccess file exists
Writing 'LimitRequestBody 0' config. to .htaccess
Saving app nextcloud in DB...
Successfully installed app nextcloud
Got signal: debug
karen is getting triggered!
time="2024-02-11T02:11:13+01:00" level=warning msg="network default: network.external.name is deprecated. Please set network.name with external: true"
Debug result file generated

Docker containers
-----------------
NAMES                   STATUS
nextcloud-web-1         Up 21 minutes
nextcloud-cron-1        Up 21 minutes
nextcloud-redis-1       Up 21 minutes
nextcloud-db-1          Up 21 minutes
nextcloud-app_proxy-1   Up 21 minutes
nginx                   Up 30 minutes
manager                 Up 30 minutes
dashboard               Up 30 minutes
auth                    Up 30 minutes
tor_proxy               Up 30 minutes

Umbrel logs
-----------

manager  | ::ffff:10.21.21.2 - - [Sun, 11 Feb 2024 01:36:47 GMT] "GET /v1/system/update-status HTTP/1.0" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
manager  | 
manager  | umbrel-manager
manager  | ::ffff:10.21.21.2 - - [Sun, 11 Feb 2024 01:36:47 GMT] "GET /v1/apps?installed=1 HTTP/1.0" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
manager  | 
manager  | umbrel-manager
manager  | ::ffff:10.21.21.2 - - [Sun, 11 Feb 2024 01:36:47 GMT] "GET /v1/system/memory HTTP/1.0" 200 217 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
manager  | 
manager  | umbrel-manager
manager  | ::ffff:10.21.21.2 - - [Sun, 11 Feb 2024 01:36:47 GMT] "GET /v1/system/storage HTTP/1.0" 200 220 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
manager  | 
manager  | umbrel-manager
manager  | ::ffff:10.21.21.2 - - [Sun, 11 Feb 2024 01:36:47 GMT] "GET /v1/apps HTTP/1.0" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
manager  | 
manager  | umbrel-manager
manager  | ::ffff:10.21.21.2 - - [Sun, 11 Feb 2024 01:36:47 GMT] "GET /v1/apps?installed=1 HTTP/1.0" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
manager  | 
manager  | umbrel-manager
manager  | ::ffff:10.21.21.2 - - [Sun, 11 Feb 2024 01:36:47 GMT] "GET /v1/system/memory HTTP/1.0" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
manager  | 
manager  | umbrel-manager
manager  | ::ffff:10.21.21.2 - - [Sun, 11 Feb 2024 01:36:47 GMT] "GET /v1/system/storage HTTP/1.0" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
manager  | 
manager  | umbrel-manager
manager  | ::ffff:10.21.21.2 - - [Sun, 11 Feb 2024 01:36:47 GMT] "GET /v1/system/get-update HTTP/1.0" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
manager  | 
manager  | umbrel-manager
manager  | ::ffff:10.21.21.2 - - [Sun, 11 Feb 2024 01:36:48 GMT] "GET /v1/system/get-update HTTP/1.0" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
manager  | 
manager  | umbrel-manager

Tor Proxy logs
--------

tor_proxy  | Feb 11 01:06:59.000 [notice] Bootstrapped 56% (loading_descriptors): Loading relay descriptors
tor_proxy  | Feb 11 01:06:59.000 [notice] Bootstrapped 62% (loading_descriptors): Loading relay descriptors
tor_proxy  | Feb 11 01:06:59.000 [notice] Bootstrapped 71% (loading_descriptors): Loading relay descriptors
tor_proxy  | Feb 11 01:06:59.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
tor_proxy  | Feb 11 01:06:59.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
tor_proxy  | Feb 11 01:06:59.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
tor_proxy  | Feb 11 01:06:59.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
tor_proxy  | Feb 11 01:07:00.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
tor_proxy  | Feb 11 01:07:00.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
tor_proxy  | Feb 11 01:07:00.000 [notice] Bootstrapped 100% (done): Done

App logs
--------

nextcloud

WARN[0000] network default: network.external.name is deprecated. Please set network.name with external: true 
redis-1  | 1:C 11 Feb 2024 01:15:57.647 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-1  | 1:M 11 Feb 2024 01:15:57.648 * monotonic clock: POSIX clock_gettime
redis-1  | 1:M 11 Feb 2024 01:15:57.648 * Running mode=standalone, port=6379.
redis-1  | 1:M 11 Feb 2024 01:15:57.648 # Server initialized
redis-1  | 1:M 11 Feb 2024 01:15:57.648 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-1  | 1:M 11 Feb 2024 01:15:57.649 * Loading RDB produced by version 6.2.2
redis-1  | 1:M 11 Feb 2024 01:15:57.649 * RDB age 2 seconds
redis-1  | 1:M 11 Feb 2024 01:15:57.649 * RDB memory usage when created 0.77 Mb
redis-1  | 1:M 11 Feb 2024 01:15:57.649 * DB loaded from disk: 0.000 seconds
redis-1  | 1:M 11 Feb 2024 01:15:57.649 * Ready to accept connections
app_proxy-1  | Retrying...
app_proxy-1  | Error wating for port: "The address 'nextcloud_web_1' cannot be found"
app_proxy-1  | Retrying...
app_proxy-1  | Error wating for port: "The address 'nextcloud_web_1' cannot be found"
app_proxy-1  | Retrying...
app_proxy-1  | Error wating for port: "The address 'nextcloud_web_1' cannot be found"
app_proxy-1  | Retrying...
app_proxy-1  | Error wating for port: "The address 'nextcloud_web_1' cannot be found"
app_proxy-1  | Retrying...
app_proxy-1  | Error wating for port: "The address 'nextcloud_web_1' cannot be found"
cron-1       | #1 /var/www/html/lib/base.php(1200): OC::init()
cron-1       | #2 /var/www/html/cron.php(43): require_once('/var/www/html/l...')
cron-1       | #3 {main}
cron-1       | crond: USER www-data pid   9 cmd php -f /var/www/html/cron.php
cron-1       | Exception: Not installed in /var/www/html/lib/base.php:283
cron-1       | Stack trace:
cron-1       | #0 /var/www/html/lib/base.php(709): OC::checkInstalled(Object(OC\SystemConfig))
cron-1       | #1 /var/www/html/lib/base.php(1200): OC::init()
db-1         | 2024-02-11  1:15:58 0 [Note] InnoDB: 10.5.12 started; log sequence number 45118; transaction id 20
cron-1       | #2 /var/www/html/cron.php(43): require_once('/var/www/html/l...')
cron-1       | #3 {main}
db-1         | 2024-02-11  1:15:58 0 [Note] Plugin 'FEEDBACK' is disabled.
db-1         | 2024-02-11  1:15:58 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db-1         | 2024-02-11  1:15:58 0 [Note] InnoDB: Buffer pool(s) load completed at 240211  1:15:58
db-1         | 2024-02-11  1:15:58 0 [Note] Server socket created on IP: '::'.
db-1         | 2024-02-11  1:15:58 0 [Warning] 'proxies_priv' entry '@% root@439ff8dd6388' ignored in --skip-name-resolve mode.
db-1         | 2024-02-11  1:15:58 0 [Note] Reading of all Master_info entries succeeded
db-1         | 2024-02-11  1:15:58 0 [Note] Added new Master_info '' to hash table
db-1         | 2024-02-11  1:15:58 0 [Note] mysqld: ready for connections.
db-1         | Version: '10.5.12-MariaDB-1:10.5.12+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
web-1        | Configuring Redis as session handler
web-1        | => Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/before-starting
web-1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.21.0.6. Set the 'ServerName' directive globally to suppress this message
web-1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.21.0.6. Set the 'ServerName' directive globally to suppress this message
web-1        | [Sun Feb 11 01:15:59.694935 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Debian) PHP/8.2.15 configured -- resuming normal operations
web-1        | [Sun Feb 11 01:15:59.695543 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
================
==== Result ====
================
==== END =====
</details>

<details>
<summary>containers on same networks</summary>
[manjaroumbrelvm scripts]# docker network connect umbrel_main_network nextcloud-app_proxy-1
Error response from daemon: endpoint with name nextcloud-app_proxy-1 already exists in network umbrel_main_network
[manjaroumbrelvm scripts]# docker network connect umbrel_main_network nextcloud_web_1
Error response from daemon: No such container: nextcloud_web_1
[manjaroumbrelvm scripts]# docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS          PORTS                                       NAMES
673bf45b6a07   nextcloud:28.0.2-apache        "/entrypoint.sh apac…"   25 minutes ago   Up 25 minutes   80/tcp                                      nextcloud-web-1
a44039e8dd42   nextcloud:28.0.2-apache        "/cron.sh"               25 minutes ago   Up 25 minutes   80/tcp                                      nextcloud-cron-1
d4f4727f073b   redis:6.2.2-buster             "docker-entrypoint.s…"   25 minutes ago   Up 25 minutes   6379/tcp                                    nextcloud-redis-1
81aacee807c1   mariadb:10.5.12                "docker-entrypoint.s…"   25 minutes ago   Up 25 minutes   3306/tcp                                    nextcloud-db-1
f91be32db191   getumbrel/app-proxy:v0.5.2     "docker-entrypoint.s…"   25 minutes ago   Up 25 minutes   0.0.0.0:8081->8081/tcp, :::8081->8081/tcp   nextcloud-app_proxy-1
21ce16826571   nginx:1.17.8                   "nginx -g 'daemon of…"   34 minutes ago   Up 34 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp           nginx
9ddc5f3f7e04   getumbrel/manager:0.5.4        "docker-entrypoint.s…"   34 minutes ago   Up 34 minutes   3006/tcp                                    manager
5a4e86199400   getumbrel/dashboard:0.5.4      "docker-entrypoint.s…"   34 minutes ago   Up 34 minutes   3004/tcp                                    dashboard
0d1187be272c   getumbrel/auth-server:v0.5.1   "docker-entrypoint.s…"   34 minutes ago   Up 34 minutes   0.0.0.0:2000->2000/tcp, :::2000->2000/tcp   auth
b860eda756e0   getumbrel/tor:0.4.7.8          "tor"                    34 minutes ago   Up 34 minutes   127.0.0.1:9050->9050/tcp                    tor_proxy
[manjaroumbrelvm scripts]# docker network connect umbrel_main_network nextcloud-web-1
Error response from daemon: endpoint with name nextcloud-web-1 already exists in network umbrel_main_network
</details>

**Comment by fran-olivares** [comment]
Fixed on the new installer script version:  replace docker-compose v2 with v1

Replace docker-compose from pacman repos v2 with AUR package docker-compose-v1-bin to fix errors starting apps after install due to network.external.name is deprecated on docker-compose v2 and Umbrel is designed and it works with docker-compose v1 on debian systems.
